library(flexdashboard)
library(knitr)
library(crosstalk)
library(DT)
library(tidyverse) 
library(plotly)
library(stringr)
library(reshape2)
library(readxl)
library(dplyr)
library(reactable)
library(formattable) 
library(base64enc)
library(png)
library(patchwork)
library(devtools) 
library(htmltools)
library(lubridate)
library(kableExtra)
library(data.table)
library(quarto)

GHG_ALL_name <- "FlatOutput_DAGHGI_1990-2022.xlsx"
GHG_PROJ_name <- "GHG Projections Data.xlsx"