project:
  type: website
  output-dir: ../docs

website:
  title: Northern Ireland Greenhouse Gas Inventory 1990-2022
  search: false
  navbar:
    logo: img/A4_DAERA_Logo_White_Out.png
    logo-alt: DAERA logo
    left:
      - href: index.qmd
        text: HOME
        icon: bi-house-door-fill
      - text: SECTOR EMISSIONS
        menu:
          - text: Northern Ireland
            href: northern-ireland.qmd
          - text: Agriculture
            href: agriculture.qmd
          - text: Building and product uses
            href: building-and-product-uses.qmd
          - text: Domestic transport
            href: domestic-transport.qmd
          - text: Electricity supply
            href: electricity-supply.qmd
          - text: Fuel supply
            href: fuel-supply.qmd
          - text: Industry
            href: industry.qmd
          - text: LULUCF
            href: lulucf.qmd
          - text: Waste
            href: waste.qmd
      - href: comparisons.qmd
        text: COMPARISONS
        icon: bi-bar-chart-fill
      - href: explore.qmd
        text: EXPLORE
        icon: bi-grid-3x3-gap-fill
      - href: user-notes.qmd
        text: USER NOTES
        icon: bi-clipboard-minus

format:
  dashboard:
    css: style.css
    fig-responsive: true
    include-in-header: 
      text: |
        <link rel="icon" type="image" href="img/favicon-daera.svg"/>
        <script src = "cookies_script.js"></script>
    include-before-body:
      text: |
        <div id = "cookie-banner"></div>
        
    
