---
title: EXPLORE
---

```{r setup}
#| include: FALSE

library(here)
source(paste0(here(), "/data_prep/explore.R"))

```

## Row {.tabset}

```{r}
#| title: Rankings Table (2022)

filter_select(id = "TESS1", label = "Select Sectors", sharedData = sharedGHG_NI_thisYr, group = ~Sector)

h2(paste0("NI Greenhouse Gas Emissions Ranking Table ", currentYear))

datatable(sharedGHG_NI_thisYr,
          colnames = c("Rank", "Sector", "Source", "Total Emissions (KtCO\u2082e)" ),
          fillContainer = FALSE,
          extensions = 'Buttons',
          options = list(
            columnDefs = list(
              list(visible = FALSE, targets = FALSE),
              list(className = "dt-right", targets = list(0,3)),
              list(className = "dt-left", targets = 1:2)),
            list(width = "10px", targets = 0),
            dom = 'Bfrtip',
            buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```

```{r}
#| title: Tree Map (2022)

alltreemap <- plot_ly(
  type="treemap",
  labels=tmap_labels,
  parents=tmap_parents,
  values= tmap_values,
  marker=list(colors= c("white",sectorColours$colour)),
  textinfo = "label",
  text = paste0(tmap_labels,": ", prettyNum(tmap_values, big.mark = ",")," KtCO\u2082e"),
  hoverinfo = 'text'
)%>%
  layout(
    hoverlabel = list(font=list(size=30))
  )

h3(span(style = "font-size: 16pt;",span(style = "font-weight: bold;", "Interactive Tree Map:"), "Click on any sector name ( e.g. Agriculture, Business etc) to have a closer look at the sub-sectors within that sector. Click the sector name again to return to the full tree map."))

alltreemap
```

```{r}
#| title: Projections

yaxistitle <- list(x = 0, y = 1, text = "Kilotonnes\nCO\u2082e", 
                   showarrow = F, xref= "paper", yref="paper", 
                   xanchor = "center", yanchor="bottom",
                   font = list(size = 12))

figProjections <- Shared_projection %>%
  plot_ly(x = ~eYear2,
  y = ~post1997,
  color = ~NCFormat,
  type = "scatter",
  mode = "lines+markers",
  colors = sectorColours$colour,
  text = lineTextProj,
  showlegend = FALSE) %>%
  add_trace(y = ~pre1997,
            mode = "markers") %>%
  add_trace(y = ~projection,
            line = list(dash = "dash")) %>%
  layout(xaxis = list(title = "",
                      tickangle = 0,
                      zeroline = FALSE),
         yaxis = list(title = "",
                      tickformat = ",d",
                      showline = TRUE),
         annotations = list(yaxistitle),
         margin = list(t = 50),
#         hovermode = "x unified",
         title = "Projected sectoral emissions in Northern Ireland", titlefont = list(size = 25),
         clickmode = "none") %>%
  config(displaylogo = FALSE)


tableProjections <- datatable(Shared_projection,
                          colnames = c("Year", "Sector", "Actual or Projected", "CO\u2082 Equivalents (kilotonnes CO\u2082e)"),
                          fillContainer = FALSE,
                          rownames = FALSE,
                          extensions = 'Buttons', options = list(
                            columnDefs = list(list(visible = FALSE, targets = 4:8),
                                              list(className = "dt-body-right", targets = c(0,3)),
                                              list(className = "dt-right", targets = c(0,3)),
                                              list(className = 'dt-left', targets = "_all")),
                            dom = 'Bfrtip',
                            buttons = list(
                              list(extend = "pdf", exportOptions = list(columns = ":visible")),
                              list(extend = "excel", exportOptions = list(columns = ":visible")),
                              list(extend = "csv", exportOptions = list(columns = ":visible")),
                              list(extend = "copy", exportOptions = list(columns = ":visible")),
                              list(extend = "print", exportOptions = list(columns = ":visible"))
                            )
                              ))



div(class = "row", style = "display: flex;",
    div(style = "width: 2%"),
    div(style = "width: 76%",
        div(style = "height: 45%", figProjections),
        div(style = "height: 50%", tableProjections),
        div(style = "height: 5%")),
    div(style = "width: 2%"),
    div(style = "width: 18%",
         filter_select(id = "NCFormat", label = "Sector", sharedData = Shared_projection, group = ~NCFormat),
         filter_slider(id = "EmissionYear", label = "Year", sharedData = Shared_projection, column = ~EmissionYear, timeFormat = "%Y"),
         filter_checkbox(id= "Source", label = "Actual/Projection", sharedData = Shared_projection, group=~Source)
        ),
    div(style = "width: 2%")
    )
```
