---
title: USER NOTES
---

```{r setup}
#| include: FALSE

library(here)
source(paste0(here(), "/data_prep/main.R"))

```

## Row {.tabset}

### NOTES

**User Notes**

**Introduction:** This dashboard presents data for Northern Ireland, from the Greenhouse Gas (GHG) Inventory. The GHG inventory provides the official estimates of emissions for the UK and each DA from 1990 to the latest available year. The inventory fulfils the United Nations Framework Convention on Climate Change (UNFCCC) reporting requirements under the Kyoto Protocol. The GHG inventory helps in understanding the amount of GHGs emitted and what sectors they originate from. The Inventory covers the emissions of the following seven gases which contribute to global warming:

-   Carbon dioxide (CO<sub>2</sub>)
-   Methane (CH<sub>4</sub>)
-   Nitrous oxide (N<sub>2</sub>O)
-   Hydrofluorocarbons (HFCs)
-   Perfluorocarbons (PFCs)
-   Sulphur hexafluoride (SF<sub>6</sub>)
-   Nitrogen trifluoride (NF<sub>3</sub>)

The last four of these gases are the Fluorinated, or F-gases.

**Global Warming Potential:** Depending on their molecular weights, radiative properties and residence times in the atmosphere, each GHG has a different capacity to cause global warming. The Global warming potential, GWP, provides a measure of how much heat a GHG traps in the atmosphere, when that gas is compared to CO<sub>2</sub>. In order to compare emissions between GHGs consistently, each gas is weighted by its GWP. The GWP defines how potent a GHG is compared to CO<sub>2</sub> (which has a GWP of 1) while all other GHGs have larger GWPs, reflecting their greater global warming effect per unit.

**CO**<sub>2</sub> Equivalent: The values in this dashboard are presented in CO<sub>2</sub> equivalent units (CO<sub>2</sub>e). This is the emissions value, weighted using the appropriate GWP for the gas type. This standardises emissions from different gases, allowing comparison. More information on GWPs is available at: [UK greenhouse gas emissions: other technical reports](https://www.gov.uk/government/publications/uk-greenhouse-gas-emissions-explanatory-notes)

When comparing emissions over time, the ‘base year’ of 1990 is used for carbon dioxide, methane and nitrous oxide and 1995 for the fluorinated gases. When comparing emissions between England, Scotland, Wales and Northern Ireland in the comparisons tab, a log-scale is used. A log-scale allows data with a wide range of values to be compared on a single graph.

**Replacement of National Communication sectors with Territorial Emissions Statistics sectors:** Previous Northern Ireland Greenhouse Gas emissions statistics categorised emissions estimates into National Communication (NC) sectors. Following consultation with key stakeholders, it was proposed that the emissions estimates be categorised into Territorial Emissions Statistics (TES) sectors in order to better meet users' needs. A breakdown of how emissions sources from NC sectors have been reallocated to TES sectors is provided below.

+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TES Sector                 | Emissions sources in scope according to their NC sector allocation                                                                                                                                                                                                                                                                                                                                                                                    |
+============================+=======================================================================================================================================================================================================================================================================================================================================================================================================================================================+
| Agriculture                | Agriculture – The coverage of the Agriculture sector is unchanged. However, there have been some changes to the categories within the Agriculture sector.                                                                                                                                                                                                                                                                                             |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Buildings and Product Uses | Business - Includes emissions from combustion on commercial sites previously allocated to the Business sector. Also includes emissons from product uses in Business such as nitrous oxide (N2O) use as an anaesthetic, or stationary refrigeration and air conditioning.\                                                                                                                                                                             |
|                            | Public - Includes all emissions previously allocated to the Public sector.\                                                                                                                                                                                                                                                                                                                                                                           |
|                            | Residential - Includes emissions from residential fuel combustion and product uses such as recreational N2O use, aerosols, and metered dose inhalers previously allocated to the Residential sector.\                                                                                                                                                                                                                                                 |
|                            | Industrial Processes - Includes emissions from the use of N2O in industry previously allocated to the Industrial Processes sector.                                                                                                                                                                                                                                                                                                                    |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Domestic transport         | Transport - includes all emissions previously allocated to the transport sector.\                                                                                                                                                                                                                                                                                                                                                                     |
|                            | Business - Includes F-gas emissions from mobile air conditioning and transport refrigeration previously categorised as part of the Business sector.                                                                                                                                                                                                                                                                                                   |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Electricity Supply         | Energy Supply - Includes emissions from power stations previously allocated to the Energy Supply sector.                                                                                                                                                                                                                                                                                                                                              |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fuel Supply                | Energy Supply - Includes emissions from fuel production and fuel supply activities such as mining, refining, manufacturing and distributing fuels previously allocated to the Energy Supply sector.                                                                                                                                                                                                                                                   |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Industry                   | Business - Most Industry sector emissions carry over from Business sector. These comrpise of emissions from manufacturing and construction, a well as industrial refrigeration and air conditioning.\                                                                                                                                                                                                                                                 |
|                            | Industrial Processes - Most emissions previously categorised as part of the Industrial processes sector have been reallocated to the Industry sector.\                                                                                                                                                                                                                                                                                                |
|                            | Energy Supply - Emissions from coke production previously categorised as part of the Energy supply sector have been reallocated to the Industry sector.                                                                                                                                                                                                                                                                                               |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Land use change            | Land use change - The coverage of the land use change sector is unchanged. However there have been some substantial changes to the categories within the land use change sector to align better with land use poliyc. Key changes include separation of forestry and peatlands related emissions into their own sub-sectors, as well as the creation of new categories within forestry and peatlands that better describe the emissions and removals. |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Waste                      | Waste management - Includes all emissions prevously allocated to the Waste management sector.\                                                                                                                                                                                                                                                                                                                                                        |
|                            | Business - Includes emissions from accidental fires previously allocated to the Business Sector.\                                                                                                                                                                                                                                                                                                                                                     |
|                            | Residential - Includes emissions from household composting, small-scale waste burning, and accidental fires previously allocated to the Residential sector.                                                                                                                                                                                                                                                                                           |
+----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Progress against draft ‘Programme for Government’ Wellbeing Framework:**  Greenhouse gas emissions have been included as an indicator under the ‘Cleaner Environment’ domain within the draft Programme for Government Wellbeing Framework. See [Programme for Government](https://www.executiveoffice-ni.gov.uk/topics/making-government-work/programme-government) for further information.

### META DATA

**MetaData**

The data in this dashboard come from [Greenhouse Gas Inventories for England Scotland, Wales and Northern Ireland](https://naei.beis.gov.uk/reports/reports?report_id=1080)

The GHG inventory data are produced annually by Ricardo Energy and Environment, on behalf of the Department for Energy Security & Net Zero, the Scottish Government, the Welsh Assembly Government and the Northern Ireland Department of Agriculture, Environment and Rural Affairs. Each year the GHG inventory is extended and updated. The entire historical data series, from 1990 to the latest year, is revised to incorporate methodological improvements and new data. This takes into account revisions to the datasets used in its compilation.

The GHG emission estimates are based on a wide range of data sources and sources of uncertainty include statistical differences, assumptions, proxy datasets and expert judgement. In addition, the natural variability in the processes that are being modelled introduce uncertainty. For example, carbon content of fuels and farming practices under different climatic conditions and soil types. Uncertainty estimates for Northern Ireland emissions are available for the base year, the latest year (2022) and for the percentage change between the two years. For the base year, a close approximation of the 95% confidence interval is ±8%, and for 2022 it is ±6%. For the percentage reduction between the base year and 2021, the 95% confidence interval ranges from 20% to 37%.

There remains greater uncertainty around emissions in Northern Ireland compared to other parts of the United Kingdom due to the relative importance of methane and nitrous oxide emissions in the agriculture sector. Emissions of this gas are more difficult to estimate than carbon dioxide, and the agriculture sector makes up a larger share of Northern Ireland’s emissions than in other parts of the UK. More information is available in [An introduction to the UK’s greenhouse gas inventory](https://www.gov.uk/government/publications/uk-greenhouse-gas-emissions-statistics-user-guidance) and [UK Greenhouse Gas Emissions Statistics: FAQs](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/996190/uk-emissions-statistics-frequently-asked-questions.pdf).

**Contact Details**

DAERA Statistics & Analytical Services Branch is keen to hear your feedback.

Please e-mail comments to [env.stats@daera-ni.gov.uk](mailto:env.stats@daera-ni.gov.uk)

Further information can be found on the [DAERA Statistics website](https://www.daera-ni.gov.uk/landing-pages/statistics).


**Date of Publication:**

Published: Annually

Time period covered – Greenhouse Gas Inventory: 1990-`r currentYear`
